/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anderson Alves
 */
public class telaLeitor extends javax.swing.JFrame {

    /**
     * Creates new form telaLeitor
     */
    public telaLeitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnNum = new javax.swing.JSpinner();
        pnTexto = new javax.swing.JPanel();
        lblExtenso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnNum.setModel(new javax.swing.SpinnerNumberModel(0, 0, 39, 1));
        spnNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnNumStateChanged(evt);
            }
        });

        lblExtenso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExtenso.setForeground(new java.awt.Color(153, 0, 255));
        lblExtenso.setText("Zero");

        javax.swing.GroupLayout pnTextoLayout = new javax.swing.GroupLayout(pnTexto);
        pnTexto.setLayout(pnTextoLayout);
        pnTextoLayout.setHorizontalGroup(
            pnTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExtenso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTextoLayout.setVerticalGroup(
            pnTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTextoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblExtenso)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnNum, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
            .addComponent(pnTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnNumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnNumStateChanged
        String numero = " ";
        int numrecebido = Integer.parseInt(spnNum.getValue().toString());

        int parada = 0;
        
        do {
        if (numrecebido <= 20) { // Condição de linha de 2 parte
            if (numrecebido == 0) {
                lblExtenso.setText("Zero");
                parada = 1;
            }else if (numrecebido == 1) {
                lblExtenso.setText(numero+ " Um");
                  parada = 1;
            }else if (numrecebido == 2) {
                lblExtenso.setText(numero+ " Dois");
                  parada = 1;
            }else if (numrecebido == 3) {
                lblExtenso.setText(numero+ " Três");
                  parada = 1;
            }else if (numrecebido == 4) {
                lblExtenso.setText(numero+ " Quatro");
                  parada = 1;
            }else if (numrecebido == 5) {
                lblExtenso.setText(numero+ " Cinco");
                  parada = 1;
            }else if (numrecebido == 6) {
                lblExtenso.setText(numero+ " Seis");
                  parada = 1;
            }else if (numrecebido == 7) {
                lblExtenso.setText(numero+ " Sete");
                  parada = 1;
            }else if (numrecebido == 8) {
                lblExtenso.setText(numero+ " Oito");
                  parada = 1;
            }else if (numrecebido == 9) {
                lblExtenso.setText(numero+ " Nove"); 
                parada = 1;
            }else if (numrecebido == 10) {
                lblExtenso.setText("Dez");
                  parada = 1;
            }else if (numrecebido == 11) {
                lblExtenso.setText("Onze");
                  parada = 1;
            }else if (numrecebido == 12) {
                lblExtenso.setText("Doze");
                  parada = 1;
            }else if (numrecebido == 13) {
                lblExtenso.setText("Treze");
                  parada = 1;
            }else if (numrecebido == 14) {
                lblExtenso.setText("Catorze");
                  parada = 1;
            }else if (numrecebido == 15) {
                lblExtenso.setText("Quinze");
                  parada = 1;
            }else if (numrecebido == 16) {
                lblExtenso.setText("Dezesseis");
                  parada = 1;
            }else if (numrecebido == 17) {
                lblExtenso.setText("Dezessete");
                  parada = 1;
            }else if (numrecebido == 18) {
                lblExtenso.setText("Dezoito");
                  parada = 1;
            }else if (numrecebido == 19) {
                lblExtenso.setText("Dezenove");
                  parada = 1;
            }else if (numrecebido == 20) {
                lblExtenso.setText("Vinte");
                  parada = 1;
            }                                              // Acima, são numeros unicos, que nao se repetem letra. Abaixo, fazemos um controle pra verificar qual familia ele pertence
        }else{ // Parte 2 
            if (numrecebido>= 21 && numrecebido<30){ // familia dos 20
               numero = "Vinte e";
               numrecebido = numrecebido - 20;  
             }else if (numrecebido == 30){      //um controle pra definir o 30
              lblExtenso.setText("Trinta");
              parada = 1;  
             }else if (numrecebido>=31 && numrecebido<40){ // Controle do 30
                 numero = "Trinta e";
                 numrecebido = numrecebido - 30;
              }
            
        }

        }while (parada != 1);
    }//GEN-LAST:event_spnNumStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLeitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblExtenso;
    private javax.swing.JPanel pnTexto;
    private javax.swing.JSpinner spnNum;
    // End of variables declaration//GEN-END:variables
}
